import Link from 'next/link';import {notFound} from 'next/navigation';import QRCode from 'qrcode';
import {session} from '@/lib/auth';import {all,str,named} from '@/lib/data';import {money,time,sumMoney} from '@/lib/format';
import {Heading,Badge,Empty} from '@/components/ui';import {FormPanel,OperationForm,type Field} from '@/components/forms';
export default async function Device({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const {client,manager}=await session();const {data:d,error}=await client.from('devices').select('*').eq('id',id).single();if(error||!d)notFound();
 const [assignments,accounts,incidents,expenses,members,projects,settings,audit]=await Promise.all([all('assignments'),all('accounts'),all('incidents'),manager?all('expenses'):Promise.resolve([]),all('members'),all('projects'),all('settings'),manager?all('audit'):Promise.resolve([])]);
 const zone=str(settings[0],'timezone'),currency=str(settings[0],'currency');const current=assignments.find(a=>a.device_id===id&&!a.returned_at);const costs=expenses.filter(e=>e.device_id===id);const url=new URL(`/devices/${id}`,process.env.NEXT_PUBLIC_APP_URL||'http://localhost:3000').href;const qr=await QRCode.toDataURL(url,{width:200,margin:1});
 const field=(name:string,label:string,type='text',required=true):Field=>({name,label,type,required,value:String(d[name]??'')});
 return <><Heading eyebrow={`INVENTARIO / ${d.code}`} title={`${d.brand} ${d.model}`} description={`${d.code} · ${d.os} · ${d.storage_gb} GB`}><Link className="secondary button" href="/devices">← Inventario</Link></Heading><div className="detail-grid"><section className="card"><div className="section-heading"><h2>Resumen del dispositivo</h2><Badge>{d.status}</Badge></div><dl className="facts">{[['Ubicación',d.location||'Sin ubicación'],['Responsable',current?named(members,current.user_id):'Sin asignación'],['Proyecto',current?named(projects,current.project_id):'Sin proyecto'],['Serie',d.serial||'No registrada'],['IMEI',d.imei||'No registrado'],['Proveedor',d.supplier||'No registrado'],['Fecha de compra',d.purchased_on||'No registrada'],['Garantía hasta',d.warranty_until||'No registrada']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="muted">{d.notes||'Sin notas operativas.'}</p><div className="tags">{d.tags.map((t:string)=><span key={t}>{t}</span>)}</div></section><section className="card qr-card"><h2>Identificación QR</h2>{/* Data URL generated locally; contains no identifiers beyond the protected route. */}<img src={qr} width={180} height={180} alt={`QR de ${d.code}`}/><p className="muted">Abre esta ficha con tu sesión autorizada.</p><a className="secondary button" href={qr} download={`${d.code}-qr.png`}>Descargar QR ↓</a></section></div>
 <section className="card"><h2>Estado técnico registrado</h2><div className="purchase-stats"><span><small>Batería</small><strong>{d.battery===null?'Sin datos':`${d.battery}%`}</strong></span><span><small>Almacenamiento libre</small><strong>{d.free_gb===null?'Sin datos':`${d.free_gb} GB`}</strong></span><span><small>Fuente y actualización</small><strong className="small">{d.telemetry_source||'Sin datos'}</strong><small>{time(d.telemetry_at,zone)}</small></span></div>{manager&&<FormPanel title="Registrar lectura manual"><OperationForm op="telemetry" hidden={{id}} fields={[field('battery','Batería (%)','number',false),field('free_gb','Almacenamiento libre (GB)','number',false)]}/></FormPanel>}<p className="muted small">No hay telemetría en vivo. Gestión MDM pendiente de configuración.</p></section>
 {manager&&<FormPanel title="Editar información del dispositivo"><OperationForm op="edit_device" hidden={{id}} confirm="¿Guardar los cambios? Para cambiar el estado de un equipo asignado, registra antes la devolución." fields={[field('code','Código interno'),field('brand','Marca'),field('model','Modelo'),{name:'os',label:'Sistema',value:d.os,options:['iOS','Android'].map(v=>({label:v,value:v}))},field('serial','Serie','text',false),field('imei','IMEI','text',false),field('storage_gb','Almacenamiento GB','number'),field('supplier','Proveedor','text',false),field('warranty_until','Garantía hasta','date',false),field('location','Ubicación','text',false),{...field('tags','Etiquetas (coma)','text',false),value:d.tags.join(',')},field('notes','Notas operativas visibles al asignado','textarea',false),{name:'status',label:'Estado',value:d.status,options:(d.status==='asignado'?['asignado']:['disponible','mantenimiento','baja']).map(v=>({label:v,value:v}))}]}/></FormPanel>}
 <section className="card"><h2>Historial de asignaciones</h2>{assignments.filter(a=>a.device_id===id).length?<div className="table-wrap"><table><thead><tr><th>Operador</th><th>Proyecto</th><th>Entrega</th><th>Devolución</th></tr></thead><tbody>{assignments.filter(a=>a.device_id===id).map(a=><tr key={str(a,'id')}><td>{named(members,a.user_id)}</td><td>{named(projects,a.project_id)}</td><td>{time(str(a,'delivered_at'),zone)}</td><td>{a.returned_at?time(str(a,'returned_at'),zone):'Activa'}</td></tr>)}</tbody></table></div>:<Empty text="Este dispositivo aún no tiene entregas registradas."/>}</section>
 <div className="detail-grid"><section className="card"><h2>Perfiles asociados</h2>{accounts.filter(a=>a.device_id===id).map(a=><p key={str(a,'id')}><a href={str(a,'url')} target="_blank" rel="noreferrer">{str(a,'name')} ↗</a> · {str(a,'platform')}</p>)}{!accounts.some(a=>a.device_id===id)&&<p className="muted">Sin perfiles autorizados asociados.</p>}<Link href="/accounts">Gestionar perfiles ↗</Link></section><section className="card"><h2>Incidencias y reparaciones</h2>{incidents.filter(i=>i.device_id===id).map(i=><div className="incident-item" key={str(i,'id')}><strong>{str(i,'title')}</strong> <Badge>{str(i,'status')}</Badge><p>{str(i,'resolution')}</p></div>)}{!incidents.some(i=>i.device_id===id)&&<p className="muted">Sin incidencias visibles.</p>}<Link href="/incidents">Gestionar incidencias ↗</Link></section></div>
 {manager&&<><section className="card"><h2>Adquisición y gastos</h2><div className="stats">{Object.entries(sumMoney(costs.map(e=>({amount:str(e,'amount'),currency:str(e,'currency')})))).map(([c,v])=><div className="cost-total" key={c}><small>{c}</small><strong>{money(v,c)}</strong></div>)}</div><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Importe</th><th>Detalle</th></tr></thead><tbody>{costs.map(e=><tr key={str(e,'id')}><td>{time(str(e,'created_at'),zone)}</td><td>{str(e,'kind')}</td><td>{money(str(e,'amount'),str(e,'currency'))}</td><td>{str(e,'description')}</td></tr>)}</tbody></table></div><FormPanel title="Registrar gasto"><OperationForm op="expense" hidden={{device_id:id}} fields={[{name:'kind',label:'Concepto',options:['reparación','accesorios','conectividad'].map(v=>({label:v,value:v}))},{name:'amount',label:'Importe',type:'number'},{name:'currency',label:'Moneda',value:currency,options:['CLP','USD','EUR'].map(v=>({label:v,value:v}))},{name:'description',label:'Descripción'}]}/></FormPanel></section><section className="card"><h2>Bitácora del equipo</h2>{audit.filter(a=>a.entity==='devices'&&a.record_id===id).slice(-30).reverse().map(a=><p className="muted" key={str(a,'id')}>{time(str(a,'created_at'),zone)} · {str(a,'action')} · {named(members,a.actor_id)}</p>)}</section></>}
 </>;
}
