import Link from 'next/link';
import {previewEnabled} from '@/lib/preview';
import {login,loginWithGoogle} from '@/app/actions';
import {configured} from '@/lib/supabase';
import {googleAvailable} from '@/lib/sign-in';
import {redirect} from 'next/navigation';
export const dynamic='force-dynamic';
export default async function Login({searchParams}:{searchParams:Promise<{error?:string;notice?:string}>}){
 const preview=previewEnabled();if(!configured()&&!preview)redirect('/setup');
 const {error,notice}=await searchParams;const google=await googleAvailable();
 return <main className="auth"><div className="auth-art"><div className="wordmark">ZERO<span>CLIPS</span></div><div><span className="eyebrow">TU OPERACIÓN, BAJO CONTROL</span><h1>Menos fricción.<br/>Más contenido.</h1><p>Organiza tus equipos, conecta a tu equipo y sigue cada producción.</p></div><small>Plataforma de operaciones · v0.1</small></div><section className="auth-form"><span className="eyebrow">BIENVENIDO A ZEROCLIPS</span><h2>Tu próximo gran clip<br/>empieza aquí.</h2><p className="muted">{preview?'El acceso es opcional. Puedes continuar al panel sin iniciar sesión.':'Accede con tu cuenta de trabajo.'}</p>{preview&&<Link className="primary button guest-entry" href="/">Continuar sin iniciar sesión →</Link>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success">{notice}</p>}<form action={login}><label>Correo electrónico<input name="email" type="email" autoComplete="username" required placeholder="nombre@empresa.com"/></label><label>Contraseña<input name="password" type="password" autoComplete="current-password" required minLength={8}/></label><button className="primary" disabled={!configured()}>Iniciar sesión →</button></form><div className="auth-divider"><span>o continúa con</span></div><form action={loginWithGoogle}><button className="secondary google-button" disabled={!google}><svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.39-.18-2.05H12v3.88h5.38a4.6 4.6 0 0 1-2 3.02v2.51h3.24c1.9-1.75 2.98-4.33 2.98-7.36Z"/><path fill="#34A853" d="M12 22c2.7 0 4.96-.9 6.61-2.41l-3.24-2.51c-.9.6-2.05.96-3.37.96-2.61 0-4.82-1.76-5.61-4.12H3.04v2.59A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.39 13.92a6 6 0 0 1 0-3.84V7.49H3.04a10 10 0 0 0 0 9.02l3.35-2.59Z"/><path fill="#EA4335" d="M12 5.96c1.47 0 2.79.5 3.82 1.5l2.87-2.87A9.61 9.61 0 0 0 12 2a10 10 0 0 0-8.96 5.49l3.35 2.59A5.99 5.99 0 0 1 12 5.96Z"/></svg>Continuar con Google</button></form>{!google&&<p className="muted small">Google está pendiente de habilitación en Supabase.</p>}<p className="muted small">Los permisos de administrador se asignan al correo autorizado después de verificar la cuenta.</p></section></main>;
}
