import Link from 'next/link';
import {notFound} from 'next/navigation';
import {session} from '@/lib/auth';
import {all,str,options,named,type Row} from '@/lib/data';
import {Heading,Badge,Empty} from '@/components/ui';
import {OperationForm,FormPanel,ReceiveForm,type Field} from '@/components/forms';
import {Inventory} from '@/components/inventory';
import {money,time,sumMoney,multiplyMoney} from '@/lib/format';
import type {Operation} from '@/lib/validation';
const titles:Record<string,[string,string]>={devices:['Dispositivos','Una vista clara de cada equipo, donde sea que esté.'],purchases:['Compras y costos','Planifica tu flota y sigue cada inversión.'],assignments:['Asignaciones','Cada equipo, con la persona y el proyecto correctos.'],projects:['Proyectos','Conecta clientes, personas y contenido.'],tasks:['Tareas','Prioridades claras para avanzar cada día.'],accounts:['Perfiles de publicación','Cuentas autorizadas, vinculadas a tu operación.'],clips:['Pipeline de clips','De la primera idea a una publicación real.'],incidents:['Incidencias','Registra, resuelve y conserva el historial.'],members:['Tu equipo','Personas y permisos de tu espacio de trabajo.'],settings:['Configuración','Preferencias, trazabilidad y gestión técnica.']};
const f=(name:string,label:string,type='text',required=true):Field=>({name,label,type,required});
const select=(name:string,label:string,values:string[],value?:string):Field=>({name,label,options:values.map(v=>({value:v,label:v})),value});
export default async function Section({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {section}=await params;if(!titles[section])notFound();const query=await searchParams;const {manager,member}=await session();if(!manager&&['purchases','members'].includes(section))notFound();
 const [members,projects,devices,accounts,settings]=await Promise.all([all('members'),all('projects'),all('devices'),all('accounts'),all('settings')]);
 const [projectMembers,metrics,expenses]=await Promise.all([section==='projects'?all('project_members'):Promise.resolve([]),section==='clips'?all('metrics'):Promise.resolve([]),section==='purchases'?all('expenses'):Promise.resolve([])]);
 const activeAssignments=section==='devices'?(await all('assignments')).filter(a=>!a.returned_at):[];
 const setting=settings[0];const zone=str(setting,'timezone');const currency=str(setting,'currency');
 const person=(name='owner_id'):Field=>({name,label:'Responsable',options:options(members.filter(m=>m.active))});
 const project:Field={name:'project_id',label:'Proyecto',options:options(projects)};
 const device:Field={name:'device_id',label:'Dispositivo',options:options(devices,'code')};
 const currencyField=select('currency','Moneda',['CLP','USD','EUR'],currency);
 const timestamp=(name:string,label:string,required=true):Field=>({...f(name,`${label} (${zone})`,'datetime-local',required),zone});
 let rows:Row[]=[],fields:Field[]=[],op:Operation='project';
 if(section==='projects'){rows=projects;fields=[f('name','Nombre'),f('client','Cliente o marca')];}
 if(section==='assignments'){rows=await all('assignments');op='assign';fields=[{...device,options:options(devices.filter(d=>d.status==='disponible'),'code')},person('user_id'),project];}
 if(section==='purchases'){rows=await all('purchases');op='purchase';fields=[f('supplier','Proveedor'),f('brand','Marca'),f('model','Modelo'),select('os','Sistema',['iOS','Android']),f('storage_gb','Almacenamiento (GB)','number'),f('quantity','Cantidad','number'),f('unit_estimate','Precio unitario estimado','number'),currencyField];if(query.filter==='pending')rows=rows.filter(r=>Number(r.received)<Number(r.quantity));if(query.currency)rows=rows.filter(r=>r.currency===query.currency);}
 if(section==='accounts'){rows=accounts;op='account';fields=[f('name','Nombre de perfil'),select('platform','Plataforma',['TikTok','Instagram','YouTube','Facebook','Otra']),f('url','URL pública','url'),project,{...device,required:false},person()];}
 if(section==='tasks'){rows=await all('tasks');op='task';fields=[f('title','Título'),project,{...device,required:false},person(),select('priority','Prioridad',['baja','media','alta']),timestamp('due_at','Vencimiento')];if(query.filter==='open')rows=rows.filter(r=>r.status!=='completada');if(query.filter==='overdue')rows=rows.filter(r=>r.status!=='completada'&&new Date(str(r,'due_at')).getTime()<Date.now());}
 if(section==='clips'){rows=await all('clips');op='clip';fields=[f('title','Título'),{name:'account_id',label:'Perfil autorizado',options:options(accounts)},f('material_url','Enlace al material','url'),timestamp('scheduled_at','Publicación programada',false)];}
 if(section==='incidents'){rows=await all('incidents');op='incident';fields=[device,f('title','Falla reportada'),select('severity','Gravedad',['baja','media','alta','crítica']),person()];if(query.filter==='open')rows=rows.filter(r=>r.status!=='resuelta');}
 if(section==='members'){rows=members;}
 const basicDevice:Field[]=[f('code','Código interno'),f('brand','Marca'),f('model','Modelo'),select('os','Sistema operativo',['iOS','Android']),f('serial','Número de serie','text',false),f('imei','IMEI','text',false),f('storage_gb','Almacenamiento (GB)','number'),f('purchased_on','Fecha de compra','date',false),f('cost','Costo de adquisición','number',false),currencyField,f('supplier','Proveedor','text',false),f('warranty_until','Garantía hasta','date',false),f('location','Ubicación','text',false),f('tags','Etiquetas separadas por coma','text',false),f('notes','Notas operativas visibles al asignado','textarea',false)];
 return <><Heading title={titles[section][0]} description={titles[section][1]}><Link className="secondary button" href="/">← Panel</Link></Heading>
 {section==='devices'?<>{manager&&<div id="new"><FormPanel title="Registrar dispositivo"><OperationForm op="device" fields={basicDevice}/></FormPanel></div>}<Inventory devices={devices.map(d=>({...d,responsible:named(members,activeAssignments.find(a=>a.device_id===d.id)?.user_id)}))} manager={manager} initialStatus={query.status??''}/></>:section==='settings'?<><section className="card"><h2>Preferencias del espacio</h2>{member.role==='administrador'?<OperationForm op="settings" fields={[currencyField,{...f('timezone','Zona horaria IANA'),value:zone}]}/>:<p>Moneda: {currency} · Zona: {zone}</p>}</section><section className="card"><h2>Gestión técnica de dispositivos</h2><p className="notice">Sin proveedor MDM conectado. El registro administrativo funciona de forma independiente.</p><div className="table-wrap"><table><thead><tr><th>Capacidad</th><th>iOS</th><th>Android</th></tr></thead><tbody>{['Telemetría','Instalación de aplicaciones','Control remoto','Borrado'].map(c=><tr key={c}><td>{c}</td><td><Badge>Pendiente de configuración</Badge></td><td><Badge>Pendiente de configuración</Badge></td></tr>)}</tbody></table></div><p className="muted">La disponibilidad se verificará por proveedor, inscripción y plataforma. No se ejecutan acciones técnicas.</p></section>{manager&&<section className="card"><h2>Bitácora</h2><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Actor</th><th>Acción</th><th>Entidad</th><th>Registro</th></tr></thead><tbody>{(await all('audit')).slice(-100).reverse().map(a=><tr key={str(a,'id')}><td>{time(str(a,'created_at'),zone)}</td><td>{named(members,a.actor_id)}</td><td>{str(a,'action')}</td><td>{str(a,'entity')}</td><td>{str(a,'record_id')}</td></tr>)}</tbody></table></div></section>}</>:<>
 {fields.length>0&&(manager||section==='incidents')&&<FormPanel title={section==='assignments'?'Registrar entrega':`Crear ${section==='projects'?'proyecto':section==='purchases'?'compra':section==='accounts'?'perfil':section==='tasks'?'tarea':section==='clips'?'clip':'incidencia'}`}><OperationForm op={op} fields={fields}/></FormPanel>}
 {section==='projects'&&manager&&<FormPanel title="Autorizar miembro en proyecto"><OperationForm op="project_member" fields={[project,person('user_id')]}/><p className="muted">Autoriza al miembro antes de asignarle dispositivos, tareas o perfiles.</p></FormPanel>}
 {section==='members'&&<p className="notice">Crea usuarios mediante el script administrativo documentado en README. Los roles se gestionan aquí por un administrador.</p>}
 <div className="section-heading"><h2>Registros <span className="count">{rows.length}</span></h2>{query.filter&&<Link href={`/${section}`}>Quitar filtro ×</Link>}</div>
 {!rows.length&&<section className="card"><Empty/></section>}
 <div className={['projects','accounts'].includes(section)?'record-grid':'record-list'}>{rows.map(r=><section className="card record" key={str(r,'id')}>
 <div className="record-heading"><h3>{str(r,'name')||str(r,'title')||str(r,'model')||named(devices,r.device_id,'code')}</h3>{r.status&&<Badge>{str(r,'status')}</Badge>}{r.role&&<Badge>{str(r,'role')}</Badge>}</div>
 {section==='projects'&&<><p className="muted">{str(r,'client')}</p><small>Miembros: {projectMembers.filter(m=>m.project_id===r.id).map(m=>named(members,m.user_id)).join(', ')||'Sin miembros'}</small></>}
 {section==='assignments'&&<><p>{named(members,r.user_id)} · {named(projects,r.project_id)}</p><p className="muted">Entrega: {time(str(r,'delivered_at'),zone)} · Devolución: {time(r.returned_at?str(r,'returned_at'):null,zone)}</p><Link href={`/devices/${r.device_id}`}>Ver ficha ↗</Link>{manager&&!r.returned_at&&<OperationForm op="return" fields={[]} hidden={{device_id:str(r,'device_id')}} label="Registrar devolución" confirm="¿Confirmas que recibiste el dispositivo?" compact/>}</>}
 {section==='purchases'&&<><p>{str(r,'brand')} · {str(r,'os')} · {str(r,'supplier')}</p><div className="purchase-stats"><span><small>Unidades recibidas</small><strong>{str(r,'received')} / {str(r,'quantity')}</strong></span><span><small>Estimado por unidad</small><strong>{money(str(r,'unit_estimate'),str(r,'currency'))}</strong></span><span><small>Presupuesto pendiente</small><strong>{money(multiplyMoney(str(r,'unit_estimate'),Number(r.quantity)-Number(r.received)),str(r,'currency'))}</strong></span></div>{Number(r.received)<Number(r.quantity)&&<FormPanel title="Recibir dispositivos"><ReceiveForm purchase={str(r,'id')} currency={str(r,'currency')} remaining={Number(r.quantity)-Number(r.received)}/></FormPanel>}</>}
 {section==='accounts'&&<><Badge>{str(r,'platform')}</Badge><p>{named(projects,r.project_id)} · {named(members,r.owner_id)}</p><p className="muted">Equipo: {named(devices,r.device_id,'code')}</p><a href={str(r,'url')} target="_blank" rel="noreferrer">Abrir perfil público ↗</a><small className="block muted">Asociación administrativa. Sin contraseñas ni publicación automática.</small></>}
 {section==='tasks'&&<><p>{named(projects,r.project_id)} · {named(members,r.owner_id)}</p><p className="muted">Vence: {time(str(r,'due_at'),zone)} · Prioridad: {str(r,'priority')}</p><OperationForm op="task_status" hidden={{id:str(r,'id')}} fields={[select('status','Estado',['pendiente','en curso','completada'],str(r,'status'))]} label="Actualizar estado" compact/></>}
 {section==='clips'&&<><p>{named(accounts,r.account_id)} · {named(members,r.owner_id)}</p><p className="muted">Programado: {time(r.scheduled_at?str(r,'scheduled_at'):null,zone)}</p><a target="_blank" rel="noreferrer" href={str(r,'material_url')}>Ver material ↗</a>{r.publication_url&&<> · <a target="_blank" rel="noreferrer" href={str(r,'publication_url')}>Ver publicación ↗</a></>}<FormPanel title="Actualizar pipeline"><OperationForm op="clip_status" hidden={{id:str(r,'id')}} fields={[select('status','Estado',['pendiente','en edición','en revisión','aprobado','publicado'],str(r,'status')),{...f('publication_url','URL de publicación','url',false),value:str(r,'publication_url')},{...timestamp('published_at','Fecha efectiva',false),value:str(r,'published_at')}]}/></FormPanel><FormPanel title="Registrar métricas"><OperationForm op="metric" hidden={{id:str(r,'id')}} fields={[f('views','Visualizaciones','number'),timestamp('measured_at','Medición'),f('source','Fuente (ej. analítica de YouTube, manual)')]}/></FormPanel>{metrics.filter(m=>m.clip_id===r.id).map(m=><p className="muted small" key={str(m,'id')}>{str(m,'views')} visualizaciones · {time(str(m,'measured_at'),zone)} · {str(m,'source')}</p>)}</>}
 {section==='incidents'&&<><p><Link href={`/devices/${r.device_id}`}>{named(devices,r.device_id,'code')}</Link> · {named(members,r.owner_id)} · Gravedad: {str(r,'severity')}</p>{r.resolution&&<p>Resolución: {str(r,'resolution')}</p>}{manager&&r.status!=='resuelta'&&<OperationForm op="incident_status" hidden={{id:str(r,'id')}} fields={[select('status','Seguimiento',['abierta','en reparación'],str(r,'status'))]} label="Actualizar seguimiento" compact/>}{manager&&r.status!=='resuelta'&&<FormPanel title="Resolver incidencia"><OperationForm op="resolve_incident" hidden={{id:str(r,'id')}} fields={[f('resolution','Resolución','textarea'),f('amount','Costo de reparación','number',false),currencyField]}/></FormPanel>}</>}
 {section==='members'&&<><p className="muted">{r.active?'Acceso activo':'Acceso desactivado'}</p>{member.role==='administrador'&&r.id!==member.id&&<OperationForm op="member" hidden={{id:str(r,'id')}} fields={[select('role','Rol',['administrador','supervisor','operador'],str(r,'role')),{name:'active',label:'Acceso',value:String(r.active),options:[{value:'true',label:'Activo'},{value:'false',label:'Desactivado'}]}]} confirm="¿Aplicar estos cambios de acceso?"/>}</>}
 </section>)}</div>
 {section==='purchases'&&<section className="card"><h2>Gastos reales registrados</h2><div className="stats">{Object.entries(sumMoney(expenses.filter(e=>!query.currency||e.currency===query.currency).map(e=>({amount:str(e,'amount'),currency:str(e,'currency')})))).map(([c,v])=><div className="cost-total" key={c}><small>{c}</small><strong>{money(v,c)}</strong></div>)}</div><div className="table-wrap"><table><thead><tr><th>Equipo</th><th>Concepto</th><th>Importe</th><th>Detalle</th></tr></thead><tbody>{expenses.filter(e=>!query.currency||e.currency===query.currency).map(e=><tr key={str(e,'id')}><td><Link href={`/devices/${e.device_id}`}>{named(devices,e.device_id,'code')}</Link></td><td>{str(e,'kind')}</td><td>{money(str(e,'amount'),str(e,'currency'))}</td><td>{str(e,'description')}</td></tr>)}</tbody></table></div></section>}
 </>}
 </>;
}
