'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {mutate,receive,type Result} from '@/app/actions';
import {toInstant,toLocal} from '@/lib/dates';
import type {Operation} from '@/lib/validation';
export type Field={name:string;label:string;type?:string;required?:boolean;options?:{value:string;label:string}[];value?:string;placeholder?:string;zone?:string};
export function OperationForm({op,fields,hidden={},label='Guardar',confirm,compact=false}:{op:Operation;fields:Field[];hidden?:Record<string,string>;label?:string;confirm?:string;compact?:boolean}){
 const [result,setResult]=useState<Result>();const [pending,start]=useTransition();const router=useRouter();
 function submit(form:FormData){if(confirm&&!window.confirm(confirm))return;const data:Record<string,unknown>={...hidden};for(const f of fields){let value=String(form.get(f.name)??'');if(f.type==='datetime-local'&&value){try{value=toInstant(value,f.zone||'America/Santiago');}catch{setResult({ok:false,message:'La hora es inválida o ambigua por el cambio de horario. Elige otra hora.'});return;}}data[f.name]=f.name==='tags'?value.split(',').map(v=>v.trim()).filter(Boolean):f.name==='active'?value==='true':value;}start(async()=>{try{const r=await mutate(op,data);setResult(r);if(r.ok)router.refresh();}catch{setResult({ok:false,message:'No se pudo guardar. Comprueba la conexión y vuelve a intentar.'});}});}
 return <form action={submit} className={compact?'operation-form compact':'operation-form'}><div className="fields">{fields.map(f=><label key={f.name}>{f.label}{f.required!==false&&<span className="required"> *</span>}{f.options?<select name={f.name} defaultValue={f.value??''} required={f.required!==false}><option value="">Seleccionar…</option>{f.options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} defaultValue={f.value} required={f.required!==false}/>:<input name={f.name} defaultValue={f.type==='datetime-local'?toLocal(f.value||'',f.zone||'America/Santiago'):f.value} type={f.type??'text'} step={f.type==='number'?'any':undefined} placeholder={f.placeholder} required={f.required!==false}/>}</label>)}</div>{result&&<p role="status" className={result.ok?'success':'error'}>{result.message}</p>}<button className="primary" disabled={pending}>{pending?'Guardando…':label}</button></form>;
}
export function FormPanel({title,children,open=false}:{title:string;children:React.ReactNode;open?:boolean}){return <details className="form-panel" open={open}><summary><span>+</span> {title}</summary><div>{children}</div></details>;}
export function ReceiveForm({purchase,currency,remaining}:{purchase:string;currency:string;remaining:number}){
 const [key,setKey]=useState(()=>crypto.randomUUID());const [result,setResult]=useState<Result>();const [pending,start]=useTransition();const router=useRouter();
 return <form className="operation-form" action={form=>{const units=String(form.get('units')).split('\n').filter(s=>s.trim()).map(line=>{const [code,serial,imei,cost,purchased_on,location]=line.split(';').map(s=>s.trim());return {code,serial,imei,cost,purchased_on,location};});start(async()=>{try{const r=await receive({purchase,request_id:key,units});setResult(r);if(r.ok){setKey(crypto.randomUUID());router.refresh();}}catch{setResult({ok:false,message:'No se confirmó la recepción. Reintenta con los mismos datos.'});}});}}><p>Pendientes: {remaining} · Costo unitario en {currency}. Una línea por equipo.</p><label>Código; serie; IMEI; costo real; fecha de compra; ubicación<textarea name="units" required placeholder="ZC-001;;;250000;2026-09-22;Oficina" rows={3}/></label><small>La recepción es atómica. Si hay un error, no se recibe ninguna unidad.</small>{result&&<p role="status" className={result.ok?'success':'error'}>{result.message}</p>}<button className="primary" disabled={pending||remaining===0}>{pending?'Recibiendo…':'Recibir equipos'}</button></form>;
}
