'use client';
import Link from 'next/link';import {useState,useTransition} from 'react';import {useRouter} from 'next/navigation';
import {Search,Download,Upload,SlidersHorizontal,Smartphone} from 'lucide-react';
import {type Row,str} from '@/lib/rows';
import {Badge,Empty} from './ui';
import {mutate} from '@/app/actions';
import {checkImport,commitImport} from '@/app/import-actions';
import {columns,exportCsv} from '@/lib/csv';
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
export function Inventory({devices,manager,initialStatus}:{devices:Row[];manager:boolean;initialStatus:string}){
 const [q,setQ]=useState(''),[status,setStatus]=useState(initialStatus),[os,setOs]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<string[]>([]),[csv,setCsv]=useState(''),[preview,setPreview]=useState<Awaited<ReturnType<typeof checkImport>>>(),[report,setReport]=useState<{row:number;ok:boolean;message:string}[]>(),[message,setMessage]=useState(''),[pending,start]=useTransition();const router=useRouter();
 const filtered=devices.filter(d=>(!status||d.status===status)&&(!os||d.os===os)&&[d.code,d.brand,d.model,d.serial,d.imei,d.location,...(d.tags as string[])].join(' ').toLowerCase().includes(q.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/20));const current=Math.min(page,pages);
 return <><div className="inventory-tools"><div className="search"><Search size={18}/><input aria-label="Buscar un dispositivo" placeholder="Buscar código, modelo, ubicación o etiqueta…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/></div><div className="toolbar-actions"><a className="secondary button" href="/api/devices/export"><Download size={16}/> Exportar CSV</a>{manager&&<label className="secondary button"><Upload size={16}/> Importar CSV<input type="file" accept=".csv" className="visually-hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>1000000){setMessage('Archivo demasiado grande (máximo 1 MB)');return;}setPreview(undefined);setReport(undefined);const text=await file.text();setCsv(text);start(async()=>{try{setPreview(await checkImport(text));}catch{setMessage('No se pudo validar el archivo.');}});}}/></label>}</div></div><div className="filter-row"><div className="filter-tabs">{[['','Todos'],['disponible','Disponibles'],['asignado','Asignados'],['mantenimiento','Mantenimiento'],['baja','Dados de baja']].map(([v,l])=><button key={v} className={status===v?'selected':''} onClick={()=>{setStatus(v);setPage(1);}}>{l}<span>{devices.filter(d=>!v||d.status===v).length}</span></button>)}</div><label className="os-filter"><SlidersHorizontal size={15}/><select aria-label="Sistema operativo" value={os} onChange={e=>{setOs(e.target.value);setPage(1);}}><option value="">Todos los sistemas</option><option>iOS</option><option>Android</option></select></label></div>
 {message&&<p role="status" className="notice">{message}</p>}
 {manager&&<details className="csv-help"><summary>Formato de importación CSV</summary><p>Encabezados en inglés. Código, marca, modelo, sistema y almacenamiento son obligatorios. Fechas AAAA-MM-DD; importes sin separador de miles. Las etiquetas se separan con comas dentro de una celda entre comillas.</p><button className="secondary" onClick={()=>download(columns.join(',')+'\n','plantilla-dispositivos.csv')}>Descargar plantilla vacía</button></details>}
 {preview&&<section className="card"><h3>Revisión de importación</h3><p>{preview.valid.length} filas válidas · {preview.errors.length} errores</p>{preview.errors.map((e,i)=><p className="error" key={i}>Fila {e.row}: {e.message}</p>)}<button className="primary" disabled={pending||!preview.valid.length} onClick={()=>{if(!confirm(`¿Importar ${preview.valid.length} filas válidas? Las inválidas se omiten.`))return;start(async()=>{try{setReport(await commitImport(csv));setPreview(undefined);router.refresh();}catch{setMessage('No se pudo completar la importación. Vuelve a validar para consultar los registros ya guardados.');}});}}>Confirmar filas válidas</button></section>}
 {report&&<section className="card"><h3>Resultado por fila</h3>{report.map(r=><p className={r.ok?'success':'error'} key={r.row}>Fila {r.row}: {r.message}</p>)}<button className="secondary" onClick={()=>download(exportCsv(report),'resultado-importacion.csv')}>Descargar reporte</button></section>}
 {manager&&selected.length>0&&<form className="bulk" action={form=>{start(async()=>{const results=[];for(const id of selected){const r=await mutate('location',{id,location:String(form.get('location')),tags:String(form.get('tags')).split(',').map(s=>s.trim()).filter(Boolean)});results.push(`${devices.find(d=>d.id===id)?.code}: ${r.message}`);}setMessage(results.join(' · '));setSelected([]);router.refresh();});}}><strong>{selected.length} seleccionados</strong><input name="location" placeholder="Nueva ubicación" required aria-label="Nueva ubicación"/><input name="tags" placeholder="Reemplazar etiquetas (coma)" aria-label="Nuevas etiquetas"/><button className="primary" disabled={pending}>Aplicar</button></form>}
 <section className="card inventory-card"><div className="table-wrap"><table><thead><tr>{manager&&<th><input type="checkbox" aria-label="Seleccionar página" checked={filtered.slice((current-1)*20,current*20).length>0&&filtered.slice((current-1)*20,current*20).every(d=>selected.includes(str(d,'id')))} onChange={e=>setSelected(e.target.checked?filtered.slice((current-1)*20,current*20).map(d=>str(d,'id')):[])}/></th>}<th>Dispositivo</th><th>Sistema</th><th>Estado</th><th>Ubicación</th><th>Responsable</th><th>Etiquetas</th><th/></tr></thead><tbody>{filtered.slice((current-1)*20,current*20).map(d=><tr key={str(d,'id')}>{manager&&<td><input type="checkbox" aria-label={`Seleccionar ${d.code}`} checked={selected.includes(str(d,'id'))} onChange={e=>setSelected(e.target.checked?[...selected,str(d,'id')]:selected.filter(id=>id!==d.id))}/></td>}<td><Link className="device-cell" href={`/devices/${d.id}`}><span className={`device-icon ${d.os==='Android'?'android':''}`}><Smartphone size={22}/></span><span><strong>{str(d,'brand')} {str(d,'model')}</strong><small>{str(d,'code')} · {str(d,'storage_gb')} GB</small></span></Link></td><td><span className="os-pill">{str(d,'os')}</span></td><td><Badge>{str(d,'status')}</Badge></td><td>{str(d,'location')||'Sin ubicación'}</td><td>{str(d,'responsible')||'Sin asignación'}</td><td><div className="tags">{(d.tags as string[]).map(t=><span key={t}>{t}</span>)}</div></td><td><Link aria-label={`Abrir ${d.code}`} href={`/devices/${d.id}`}>↗</Link></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="No hay dispositivos que coincidan con tus filtros."/>}<div className="pagination"><span>{filtered.length} dispositivos · Página {current} de {pages}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>← Anterior</button><button disabled={current===pages} onClick={()=>setPage(current+1)}>Siguiente →</button></div></div></section></>;
}
