'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
type ScreenShareContextValue={stream:MediaStream|null;deviceCode:string|null;source:'screen'|'camera'|null;connect:(deviceCode:string)=>Promise<void>;connectCamera:(deviceCode:string)=>Promise<void>;disconnect:()=>void;error:string};
const ScreenShareContext=createContext<ScreenShareContextValue|null>(null);
export function ScreenShareProvider({children}:{children:React.ReactNode}){
 const [stream,setStream]=useState<MediaStream|null>(null);const [deviceCode,setDeviceCode]=useState<string|null>(null);const [source,setSource]=useState<'screen'|'camera'|null>(null);const [error,setError]=useState('');
 useEffect(()=>{if(!stream)return;const track=stream.getVideoTracks()[0];const ended=()=>{setStream(null);setDeviceCode(null)};track?.addEventListener('ended',ended);return()=>track?.removeEventListener('ended',ended)},[stream]);
 useEffect(()=>()=>stream?.getTracks().forEach(track=>track.stop()),[stream]);
 async function connect(code:string){setError('');try{if(!navigator.mediaDevices?.getDisplayMedia)throw new Error('Tu navegador no permite compartir pantalla.');const next=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:15,max:30}},audio:false});stream?.getTracks().forEach(track=>track.stop());setStream(next);setDeviceCode(code);setSource('screen')}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(e instanceof Error?e.message:'No se pudo conectar la pantalla.')}}
 async function connectCamera(code:string){setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Tu navegador no permite cámaras locales.');let devices=await navigator.mediaDevices.enumerateDevices();let cameras=devices.filter(d=>d.kind==='videoinput'&&/obs|virtual/i.test(d.label));if(!cameras.length){const permission=await navigator.mediaDevices.getUserMedia({video:true,audio:false});permission.getTracks().forEach(track=>track.stop());devices=await navigator.mediaDevices.enumerateDevices();cameras=devices.filter(d=>d.kind==='videoinput'&&/obs|virtual/i.test(d.label));}if(!cameras.length)throw new Error('No se encontró OBS Virtual Camera. Inicia la cámara virtual en OBS y vuelve a intentar.');const next=await navigator.mediaDevices.getUserMedia({video:{deviceId:{exact:cameras[0].deviceId},frameRate:{ideal:30,max:30}},audio:false});stream?.getTracks().forEach(track=>track.stop());setStream(next);setDeviceCode(code);setSource('camera')}catch(e){if(e instanceof DOMException&&e.name==='NotAllowedError'){setError('El navegador bloqueó el acceso a la cámara virtual. Permítelo para ZEROCLIPS y reintenta.');return}setError(e instanceof Error?e.message:'No se pudo conectar OBS Virtual Camera.')}}
 function disconnect(){stream?.getTracks().forEach(track=>track.stop());setStream(null);setDeviceCode(null);setSource(null);setError('')}
 const value=useMemo(()=>({stream,deviceCode,source,connect,connectCamera,disconnect,error}),[stream,deviceCode,source,error]);return <ScreenShareContext.Provider value={value}>{children}</ScreenShareContext.Provider>;
}
export function useScreenShare(){const value=useContext(ScreenShareContext);if(!value)throw new Error('useScreenShare debe usarse dentro de ScreenShareProvider');return value;}
