import {PGlite} from '@electric-sql/pglite';
import {readFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
async function main(){
const directory=await mkdtemp(join(tmpdir(),'zeroclips-db-'));let db=new PGlite(directory);let checks=0;
async function ok(label:string,fn:()=>Promise<void>){await fn();console.log(`✓ ${label}`);checks++;}
async function denied(fn:()=>Promise<unknown>){await assert.rejects(fn);}
async function rows(sql:string,params:unknown[]=[]){return (await db.query<Record<string,unknown>>(sql,params)).rows;}
const admin='11111111-1111-4111-8111-111111111111',supervisor='22222222-2222-4222-8222-222222222222',operator='33333333-3333-4333-8333-333333333333',other='44444444-4444-4444-8444-444444444444';
async function as(id:string,role='authenticated'){await db.exec(`reset role; set role ${role};`);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);}
async function op(name:string,data:unknown){return (await rows('select public.operate($1,$2::jsonb) id',[name,JSON.stringify(data)]))[0].id as string;}
try{
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create table auth.sessions(id uuid primary key,user_id uuid);create table auth.refresh_tokens(id bigint primary key,user_id text);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
await ok('La migración se aplica a PostgreSQL vacío',async()=>{await db.exec(await readFile('supabase/migrations/202609220001_core.sql','utf8'));});
for(const [id,name] of [[admin,'Admin'],[supervisor,'Supervisor'],[operator,'Operador'],[other,'Otro']])await db.query('insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)',[id,`${name}@example.test`,JSON.stringify({name,role:'administrador'})]);
await ok('Metadatos del usuario no permiten escalar privilegios',async()=>{assert.equal((await rows('select role from public.members where id=$1',[operator]))[0].role,'operador');});
await db.query("update public.members set role='administrador' where id=$1",[admin]);await db.query("update public.members set role='supervisor' where id=$1",[supervisor]);
await as('', 'anon');await ok('Anónimo no puede leer inventario ni ejecutar operaciones',async()=>{await denied(()=>rows('select * from public.devices'));await denied(()=>op('project',{name:'Intruso',client:'X'}));});
await as(admin);const project=await op('project',{name:'Proyecto A',client:'Marca A'});await op('project_member',{project_id:project,user_id:operator});
const purchase=await op('purchase',{supplier:'Proveedor',brand:'Apple',model:'iPhone',os:'iOS',storage_gb:128,quantity:2,unit_estimate:'250000',currency:'CLP'});
const request='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';const units=[{code:' zc-001 ',cost:'240000',purchased_on:'2026-09-22'}];
const receive=(key:string,list:unknown[])=>rows('select public.receive_purchase($1,$2,$3::jsonb)',[purchase,key,JSON.stringify(list)]);
await ok('Recepción parcial e idempotencia sin duplicar costos',async()=>{await receive(request,units);await receive(request,units);assert.equal((await rows('select count(*)::int n from public.devices'))[0].n,1);assert.equal((await rows('select sum(amount)::text amount from public.expenses'))[0].amount,'240000.00');await denied(()=>receive(request,[{...units[0],cost:'1'}]));});
await ok('Recepción inválida o excesiva revierte la transacción',async()=>{await denied(()=>receive('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',[{code:'ZC-002',cost:'10',purchased_on:'2026-09-22'},{code:'ZC-003',cost:'10',purchased_on:'2026-09-22'}]));await denied(()=>receive('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',[{code:'ZC-001',cost:'10',purchased_on:'2026-09-22'}]));assert.equal((await rows('select received from public.purchases where id=$1',[purchase]))[0].received,1);});
await ok('Una segunda unidad inválida revierte la recepción completa',async()=>{const second=await op('purchase',{supplier:'Test',brand:'Apple',model:'Test',os:'iOS',storage_gb:128,quantity:2,unit_estimate:'1',currency:'CLP'});const list=[{code:'ROLLBACK-1',cost:'1',purchased_on:'2026-09-22'},{code:'ZC-001',cost:'1',purchased_on:'2026-09-22'}];await denied(()=>rows('select public.receive_purchase($1,$2,$3::jsonb)',[second,'cccccccc-cccc-4ccc-8ccc-cccccccccccc',JSON.stringify(list)]));assert.equal((await rows("select count(*)::int n from public.devices where code='ROLLBACK-1'"))[0].n,0);assert.equal((await rows('select received from public.purchases where id=$1',[second]))[0].received,0);});
await receive('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',[{code:'ZC-002',cost:'245000',purchased_on:'2026-09-22'}]);const device=(await rows("select id from public.devices where code='ZC-001'"))[0].id as string;const device2=(await rows("select id from public.devices where code='ZC-002'"))[0].id as string;
await ok('Código normalizado, serie e IMEI únicos; nulos repetibles',async()=>{const data={code:'zc-003',brand:'Samsung',model:'S',os:'Android',storage_gb:128,serial:' serial-a ',imei:'012345678901234',currency:'USD',cost:'10.10',purchased_on:'2026-09-22'};await op('device',data);await denied(()=>op('device',{...data,code:'ZC-004',imei:'112345678901234'}));await denied(()=>op('device',{...data,code:'ZC-004',serial:'B'}));await denied(()=>op('device',{...data,code:' zc-001 ',serial:'C',imei:'212345678901234'}));});
await ok('Entrega incompatible bloqueada y solo una asignación activa',async()=>{await op('assign',{device_id:device,user_id:operator,project_id:project});await denied(()=>op('assign',{device_id:device,user_id:operator,project_id:project}));assert.equal((await rows('select count(*)::int n from public.assignments where device_id=$1 and returned_at is null',[device]))[0].n,1);await denied(()=>op('member',{id:operator,role:'operador',active:false}));});
const account=await op('account',{name:'Marca',platform:'TikTok',url:'https://www.tiktok.com/@marca',project_id:project,device_id:device,owner_id:operator});
const task=await op('task',{title:'Editar',project_id:project,device_id:device,owner_id:operator,priority:'alta',due_at:'2026-09-20T18:00:00Z'});
const clip=await op('clip',{title:'Clip 1',account_id:account,material_url:'https://example.com/material'});
await as(operator);let incident='';
await ok('Operador ve recursos propios, no costos, terceros ni bitácora',async()=>{assert.equal((await rows('select * from public.devices')).length,1);for(const t of ['purchases','expenses','audit'])assert.equal((await rows(`select * from public.${t}`)).length,0);assert.equal((await rows('select * from public.members')).length,1);await denied(()=>op('purchase',{quantity:1}));await denied(()=>rows("update public.members set role='administrador'"));await denied(()=>op('member',{id:other,role:'administrador',active:true}));});
await ok('Operador actualiza tarea, clip y reporta incidencia autorizados',async()=>{await op('task_status',{id:task,status:'en curso'});await op('clip_status',{id:clip,status:'en edición'});await denied(()=>op('clip_status',{id:clip,status:'publicado'}));await op('clip_status',{id:clip,status:'publicado',publication_url:'https://example.com/publicacion',published_at:'2026-09-22T18:00:00Z'});await op('metric',{id:clip,views:100,source:'Manual: panel TikTok',measured_at:'2026-09-22T19:00:00Z'});incident=await op('incident',{device_id:device,title:'Pantalla rota',severity:'alta',owner_id:operator});await denied(()=>op('incident',{device_id:device2,title:'No autorizado',severity:'alta',owner_id:operator}));});
await as(other);await ok('Otro operador no ve ni modifica recursos mediante IDs directos',async()=>{for(const t of ['devices','projects','tasks','accounts','clips','metrics','incidents','assignments'])assert.equal((await rows(`select * from public.${t}`)).length,0);await denied(()=>op('task_status',{id:task,status:'completada'}));await denied(()=>op('clip_status',{id:clip,status:'aprobado'}));await denied(()=>op('metric',{id:clip,views:1,source:'Manual',measured_at:'2026-09-22T19:00:00Z'}));await denied(()=>op('location',{id:device,location:'Otra',tags:[]}));});
await as(supervisor);await ok('Supervisor opera, pero no cambia roles',async()=>{await denied(()=>op('member',{id:operator,role:'administrador',active:true}));await op('resolve_incident',{id:incident,resolution:'Cambio de pantalla',amount:'50000',currency:'CLP'});await denied(()=>op('resolve_incident',{id:incident,resolution:'Reintento',amount:'50000',currency:'CLP'}));});
await ok('Costos separados por moneda y reparación contada una sola vez',async()=>{const totals=await rows('select currency,sum(amount)::text total from public.expenses group by currency order by currency');assert.deepEqual(totals,[{currency:'CLP',total:'535000.00'},{currency:'USD',total:'10.10'}]);assert.equal((await rows('select count(*)::int n from public.expenses where incident_id=$1',[incident]))[0].n,1);});
await ok('Devolución conserva historia y permite reasignar',async()=>{await op('return',{device_id:device});await op('assign',{device_id:device,user_id:operator,project_id:project});assert.equal((await rows('select count(*)::int n from public.assignments where device_id=$1',[device]))[0].n,2);await op('return',{device_id:device});});
await db.exec('reset role');await db.query('insert into auth.sessions(id,user_id) values($1,$1)',[operator]);await db.query('insert into auth.refresh_tokens(id,user_id) values(1,$1)',[operator]);await as(admin);await op('member',{id:operator,role:'operador',active:false});await as(operator);await ok('Usuario desactivado pierde acceso aunque tenga JWT',async()=>{assert.equal((await rows('select * from public.tasks')).length,0);await denied(()=>op('task_status',{id:task,status:'completada'}));});
await db.exec('reset role');await ok('Desactivación elimina sesiones y tokens de refresco',async()=>{assert.equal((await rows('select count(*)::int n from auth.sessions'))[0].n,0);assert.equal((await rows('select count(*)::int n from auth.refresh_tokens'))[0].n,0);});
await db.close();db=new PGlite(directory);await ok('Los datos persisten después de cerrar y reabrir PostgreSQL',async()=>{assert.equal((await rows('select count(*)::int n from public.devices'))[0].n,3);assert.equal((await rows('select count(*)::int n from public.assignments'))[0].n,2);});
console.log(`\n${checks} verificaciones PostgreSQL aprobadas. PGlite usa el motor PostgreSQL, con auth.uid() simulado para RLS; no prueba el servicio Supabase Auth ni concurrencia de conexiones.`);
}finally{await db.close();await rm(directory,{recursive:true,force:true});}}
main().catch(e=>{console.error(e);process.exitCode=1;});
